### PR TITLE
Refactor EntityBuilder constraint trait for is expression

### PR DESCRIPTION
**Pull request by iK4tsu**

### CODE REVIEW

**Comment by iK4tsu** [comment]
Because `E` is only used in the `is` expression I can name it to a character that is less evasive like `_`.
```d
is(EntityManagerT == _!T, alias _ = .EntityManagerT, T)
```

**Review by ljmf00 — CHANGES_REQUESTED** [review]
I would suggest adding a link to the corresponding issue for this workaround.

https://issues.dlang.org/show_bug.cgi?id=22193

**Comment by iK4tsu** [comment]
> I would suggest adding a link to the corresponding issue for this workaround.
> 
> [issues.dlang.org/show_bug.cgi?id=22193](https://issues.dlang.org/show_bug.cgi?id=22193)

I said a workaround in that issue but technically it's not really a work around if it is a propper `is` expression syntax and used as examples in the spec.

Also, what about my first comment?

**Comment by ljmf00** [comment]
> > I would suggest adding a link to the corresponding issue for this workaround.
> > [issues.dlang.org/show_bug.cgi?id=22193](https://issues.dlang.org/show_bug.cgi?id=22193)
> 
> I said a workaround in that issue but technically it's not really a workaround if it is a propper `is` expression syntax and used in examples in the spec.

Sure. My idea to reference that is to check if the issue is solved and make it fancier whenever someone reads that code.

> Also, what about my first comment?

> Because `E` is only used in the `is` expression I can name it to a character that is less evasive like `_`.
> 
> ```d
> is(EntityManagerT == _!T, alias _ = .EntityManagerT, T)
> ```

I would prefer `E` but that's a preference. Also, that alias is only at the `is` expression scope so it doesn't interfere with other symbols.

**Pull request merged**
